import type { Metadata } from 'next';
import '../styles/globals.css';

import { Urbanist } from 'next/font/google';

// Initialize the Urbanist font with the weights you need
const urbanist = Urbanist({
  subsets: ['latin'],
  display: 'swap',
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-urbanist',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};


export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${urbanist.variable}`}>
      <body className="font-urbanist">{children}</body>
    </html>
  );
}